### ISSUE TITLE
Code give Wrong answer ,and work only for complete graphs??

### ISSUE THREAD

**Issue by surfni** [marcindziadus/parallel-mst#2]
The program fails for 
10 9
0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 
1 2 3 4 5 6 7 8 9 0 2 3 4 5 6 7 8 9 0 1 3 4 5 6 7 8 9 0 1 2 4 5 6 7 8 9 0 1 2 3 5 6 7 8 9 0 1 2 3 4 6 7 8 9 0 1 2 3 4 5 7 8 9 0 1 2 3 4 5 6 8 9 0 1 2 3 4 5 6 7 9 0 1 2 3 4 5 6 7 8 
69 161 194 12 56 62 154 148 135 69 147 77 51 187 9 133 100 55 161 147 19 72 79 14 53 193 141 194 77 19 140 16 41 10 59 146 12 51 72 140 171 136 114 33 101 56 187 79 16 171 54 48 123 88 62 9 14 41 136 54 157 58 12 154 133 53 10 114 48 157 134 16 148 100 193 59 33 123 58 134 98 135 55 141 146 101 88 12 16 98 
Is the code only work for complete graphs??

**Comment by marcindziadus** [comment]
The second number of the input sequence specifies the number of edges in an input graph.
It looks that you intend to add much more than only nine edges...
Also, the algorithm should work for connected graphs of any kind, not necessarily complete ones.

**Comment by surfni** [comment]
Actually it was 90 instead 9 But still it gives a wrong answer 
I guess i am doing something wrong 
I used these commands to run your code
g++ -c playground.cpp
nvcc -c mst.cu 
nvcc -o program playground.o mst.o
when i run ./program
and enter even small input such as 
2 1
1 
2
3
i get the answer of MST as 1 which is wrong.Please correct me if i am doing something wrong
Thanks a lot for replying

**Comment by marcindziadus** [comment]
Please note that vertices are numbered from 0, not 1! Thereon the above test is invalid.
What is your output for the more complex test?

**Comment by marcindziadus** [comment]
There is one more tacit assumption - any edge should occur exactly twice in an input sequence.
In other words, any edge is represented as two directed edges of the same weight.
I see that the bigger input preserves that condition though...

**Comment by marcindziadus** [comment]
Also, you may build the binary using just one command: nvcc mst.cu playground.cpp -g -o program :)

**Comment by surfni** [comment]
Thank Fine ,So the code is is not working for that bigger graph then right??And the contraint is the graph has to be connected as well??

**Comment by marcindziadus** [comment]
Well, a graph need to be connected to have a spanning tree, right?
I am asking once again - what is your output for the bigger one?

**Comment by surfni** [comment]
Ohh fine i was thinking it gives a spanning forest.For the given input 
serial algo gives 173 as cost 
 but your algo is giving 270
Thanks a lot again for the reply

**Comment by marcindziadus** [comment]
How would you define MST for a directed graph? It does not have much sense in general I suppose...

**Comment by surfni** [comment]
Actaully MST exist for Directed graphs.But it is fine if your code isnt working for it because i just wanted to know how to implement the MST in Cuda.I know it is relly tough to do it as well.Is the code having problem ??Like do you know why is it failing for the test case i gave??

**Comment by marcindziadus** [comment]
It works perfectly fine, at least on my machine... The returned MST has weight 173.
AFAIK, the spanning tree problem for directed graphs is completely different and significantly harder that the undirected version. My point was, that it does not make any sense to expect that both versions are solvable by a single algorithm.

**Comment by surfni** [comment]
Ohh is it?? how can the answer depend machine??  can you please give some suggestion ??
I understand what your are telling.What algo are you using to build MST??

**Comment by marcindziadus** [comment]
Honestly, I have no idea how the execution can depend on an environment.
Three years have passed since I wrote my last CUDA application...
I used Borouvka's algorithm.

**Comment by marcindziadus** [comment]
I am afraid I cannot help you and spend any more time on this.
Good luck in your investigation though!

**Comment by surfni** [comment]
Ohh fine thanks a lot

**Comment by marcindziadus** [comment]
It works perfectly fine, you need to sanitize the input only.
I feel like you are wasting my time, you do not spend even a minute to make sure that the input is in the expected form. Again...

**Comment by marcindziadus** [comment]
It should be:
3 6
0 0 1 1 2 2
1 2 0 2 0 1
67 46 67 75 46 75

So called "compressed adjacency lists representation".

**Comment by surfni** [comment]
I am sorry i didnt get that. It is working fine.Thanks a lot again.And my last question will be where can i find resource to understand your code and compressed adjacency list? and you can  choose to answer it or not a thumbs up  from my side for this project.

**Comment by marcindziadus** [comment]
The paper mentioned in README should be useful - the implementation closely follows ideas described in it. It will give you an overview of the general approach and also understanding of the implementation details. Just google it.

Sorry for my harsh answer - I am just allergic to people who ask first, instead of spending a few minutes figuring things out by themselves.
